# @package _global_

environment:
  id: ALE/Breakout-v5
  train_from_pixels: True

experiment:
  warm_up: 10_000
  cool_down: 10_000
  training_steps: 1_000_000
  testing_episodes: 10
  replay_memory:
    batch_size: 512

agent:
  critic:
    approximator:
      device: cpu
      hidden_size: 512
      encoder:
        id: ConvEncoder
        conv_channels: [32, 64, 64]
        conv_kernels: [8, 4, 3]
        conv_strides: [4, 2, 1]
        bias: False
