# @package _global_

environment:
  id: Gym-Gridworlds/FourRooms-Wall-7x7-v0
  infinite_horizon: True
  loop_through_start_pos: True

experiment:
  warm_up: 1
  cool_down: 0
  training_steps: 10_000
  testing_episodes: 4
