# @package _global_

environment:
  id: Gym-Gridworlds/FourRooms-Loop-13x13-v0
  random_goals: False
  start_pos: [[1, 1]]

experiment:
  replay_memory:
    rho: null
  warm_up: 10_000
  cool_down: 10_000
  training_steps: 200_000
  testing_episodes: 1
