# @package _global_

environment:
  id: Gym-MinAtar/Breakout-v1
  no_trail: False
  # window_size: [32, 32]
  train_from_pixels: True

experiment:
  warm_up: 10_000
  cool_down: 10_000
  training_steps: 1_000_000
  testing_episodes: 10

agent:
  critic:
    gamma: 0.999
    approximator:
      device: cpu
      hidden_size: 128
      encoder:
        id: ConvEncoder
        conv_channels: [16, 32, 32]
        conv_kernels: [3, 3, 3]
        conv_strides: [1, 1, 1]
        conv_paddings: [1, 1, 1]
        adaptive_pool: True
        bias: False
