# @package _global_

# Expected seeds per algorithm / environment.
rng_seed: 10

# Keys to be ignored when matching configs
# ignored_cfg_keys:
#   if your sweep fixes some keys that are different from defaults,
#   list them here or no run will match the plot config

plots_rows_cols: [1, -1]  # defines how to arrange subplots (optional; default [1, -1] → one row)
legend_rows_cols: [1, -1]  # defines how to arrange legend entries (optional; default [1, -1] → one row)

per_env_plot:
  show: true  # generates separates per-environment figures with all statistics
  rows_cols: [1, -1]  # optional; -1 = as many as it takes. Default [1, -1] = one row

# Configurations to plot.
# Configurations under the same group are assigned the same color but with
# different shade (from darker to lighter).
# Group names can be anything, they don't affect plotting. Here they are
# "eps_greedy", "resmax", "greedy", "random".
# In this case, the group "eps_greedy" has 2 configurations, and they will share
# the same base color.
#
# Note: nonlinearity, hidden_size, dropout_p are swept in configs/sweeps/example.yaml
# but if they are not defined here, the default values will be used.
configs:
  eps_greedy:  # can be any name
    - algorithm: eps_greedy
      agent.actor.eps.init_value: 1.0
      agent.actor.eps.end_value: 0.0
      agent.critic.approximator.nonlinearity: SiLU
      plot.label: "ε-greedy (1 → 0)"
    - algorithm: eps_greedy
      agent.actor.eps.init_value: 0.5
      agent.actor.eps.end_value: 0.2
      agent.critic.approximator.nonlinearity: LeakyReLU
      plot.label: "ε-greedy (0.5 → 0.2)"
  resmax:
    - algorithm: resmax
      agent.critic.approximator.hidden_size: 32
      plot.label: "Resmax"
  greedy:
    - algorithm: greedy
      plot.label: "Greedy"
      agent.critic.approximator.dropout_p: 0.1
  random:
    - algorithm: random
      plot.label: "Random"
      agent.critic.approximator.dropout_p: 0.0

# Environments to plot.
# You can customize the y-lim of statistics for better visualization.
environments:
  gridworlds:
    large:
      label: "Large"
      ylim:
        train: [0, 1.05]
        "train (γ)": [0, 1.05]
        test: [0, 1.05]
        "test (γ)": [0, 1.05]
    four_rooms:
      label: "FourRoom"
      ylim:
        train: [0, 1.05]
        "train (γ)": [0, 1.05]
        test: [0, 1.05]
        "test (γ)": [0, 1.05]
    travel_field_small:
      label: "TravelFieldSmall"
      ylim:
        train: [-20, 15]
        "train (γ)": [-20, 15]
        test: [-20, 15]
        "test (γ)": [-20, 15]

# Statistics to plot.
statistics:
  train: "Train Return"
  "train (γ)": "Train Return (γ)"
  test: "Test Return"
  "test (γ)": "Test Return (γ)"
  sa_h: "Entropy"
  sa_%: "Coverage"
  td_err: "Squared TD Error"
