# @package _global_
defaults:
  - override /agent: svf
  - _self_

agent:
  critic:
    id: QEnsemble
    n_critics: 4
    critics_id: QVisitNetwork
    relabeling:
      id: her_future
      K: 4

  actor:
    id: AdaGoal
    batch_size_goal: 2500
    random_tail: True
    per_step_selection: False
    goal_value_check: False
    eps:
      id: LinearDecay
      init_value: 1.0
      end_value: 0.1
      steps: ${experiment.warm_up}
      constant_init_steps: ${experiment.warm_up}

experiment:
  replay_memory:
    rho: null
