defaults:
  - agent: default
  - algorithm: random
  - environment: mini
  - wandb: default
  - hydra: default
  - _self_

results:
  data_dir: null
  save_memory: False
  save_videos: False
  save_heatmaps: False
  force_run: True
  progress_report: history_table
  slurm_debug: False

meta:
  slurm_job_id: null
  git_hash: null

experiment:
  rng_seed: 0
  testing_points: 100
  update_frequency: 1
  updates_per_step: 1
  replay_memory:
    id: OnlineMemory
    max_size: ${experiment.training_steps}
    min_size: 0
