default:
  - gcrl/default

statistics:
  sa_h: "Bin Entropy"
  sa_%: "Bin Coverage"
  sa_h_knn: "kNN Entropy"

configs:
  sun_ratio_adaptive:
    - algorithm: sun_ratio_adaptive
      experiment.replay_memory.rho: 0.5
      plot.label: "SUN"
  adagoal:
    - algorithm: adagoal
      plot.label: "AdaGoal"
  discover:
    - algorithm: discover
      plot.label: "DISCOVER"
  random:
    - algorithm: random
      plot.label: "Random"

environments:
  lunar_lander_full:
    label: "LunarLander(Full)"
    counter: "BinnedCountLunarLanderFull"
